# Numpy Basic

In [2]:
import numpy as np
np.__version__

'1.24.2'

#### Adding two arrays

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3], dtype = 'int32')
arr3 = arr1 + arr2
print(arr3)

[2 4 6]


#### get data type && size && Total size

In [14]:
print("Type:", arr2.dtype)
print("Size of array:", arr2.size)
print("Size of one element:", arr2.itemsize)
print("Total Size:", arr2.nbytes)

Type: int32
Size of array: 3
Size of one element: 4
Total Size: 12


## Multi_Dimensional array Basics

In [11]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
arr3D = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print("arr2D:", arr2D)
print("arr3D:", arr3D)

arr2D: [[1 2 3]
 [4 5 6]]
arr3D: [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


#### get dimensions

In [12]:
print("arr2D:", arr2D.ndim)
print("arr3D:", arr3D.ndim)

arr2D: 2
arr3D: 3


#### get Shape

In [13]:
print(arr2D.shape)
print(arr3D.shape)

(2, 3)
(1, 3, 3)


## Copy issue handled (Numpy)

#### Bug

In [42]:
arr1 = np.array([1, 2, 3])
arr2 = arr1
arr2[1] = 5

print ('arr1: ', arr1)
print ('arr2: ', arr2)

arr1:  [1 5 3]
arr2:  [1 5 3]


#### Fix

In [43]:
arr1 = np.array([1, 2, 3])
arr2 = arr1.copy()
arr2[1] = 5

print('arr1: ', arr1)
print('arr2: ', arr2)


arr1:  [1 2 3]
arr2:  [1 5 3]


## Accessing/Changing specific elements, rows, columns, etc.

In [12]:
arr2D = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print("arr2D:", arr2D)
print("arr3D:", arr3D)


arr2D: [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr3D: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


#### get specific index value

In [17]:
print("arr2D:", arr2D[1, 1])
print("arr3D:", arr3D[1, 1, 1])


arr2D: 5
arr3D: 11


#### get specific row && column

In [26]:
print("Row:-")
print("arr2D:", arr2D[0, :])

print("\nColumn:-")
print("arr2D:", arr2D[:, 0])

print("\nRow [1->2]:-")
print("arr2D:", arr2D[0, 1: 2])


Row:-
arr2D: [91  2  3]

Column:-
arr2D: [91  4  7]

Row [1->2]:-
arr2D: [2]


#### changing value

In [27]:
print("arr2D {Before change}:", arr2D)
arr2D[0, 0] = 91
print("\narr2D {After change}:", arr2D)

arr2D {Before change}: [[91  2  3]
 [ 4  5  6]
 [ 7  8  9]]

arr2D {After change}: [[91  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [28]:
print("arr2D {Before change}:", arr2D)
arr2D[1, 0] = arr2D[0, 0]
print("\narr2D {After change}:", arr2D)


arr2D {Before change}: [[91  2  3]
 [ 4  5  6]
 [ 7  8  9]]

arr2D {After change}: [[91  2  3]
 [91  5  6]
 [ 7  8  9]]


## Initializing Different types of Arrays

#### Initialize array with 0s

In [12]:
arr = np.zeros((2,2), dtype = 'int32')
print(arr)

[[0 0]
 [0 0]]


#### Initialize array with 1s

In [10]:
arr = np.ones((2, 2))
print(arr)


[[1. 1.]
 [1. 1.]]


#### Initialize array with same data

In [14]:
arr = np.full((2,2), 91)
print(arr)

[[91 91]
 [91 91]]


#### Initialize same structure array with same other data

In [17]:
arr2 = np.full_like(arr, 2)
print(arr2)

[[2 2]
 [2 2]]


#### Initialize array with random data

In [20]:
arr = np.random.rand(2,2)
print(arr)

[[0.79605027 0.9532402 ]
 [0.3428798  0.00303103]]


#### Initialize same structure array with random data

In [27]:
arr = np.random.random_sample(arr2.shape)
print(arr)


[[0.44946068 0.72778857]
 [0.2962834  0.0092902 ]]


#### Initialize with random integers with range

In [29]:
arr = np.random.randint(1, 10, size = (3,3))
print(arr)

[[1 7 6]
 [4 2 5]
 [9 7 7]]


#### Identity matrix formation

In [33]:
arr = np.identity(3, dtype = 'int32')
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### initialize array with repeated values

In [37]:
arr = np.array([1,2,3])
arrRep = np.repeat(arr, 3, axis = 0)
print(arrRep)

[1 1 1 2 2 2 3 3 3]


In [38]:
arr = np.array([[1, 2, 3]])
arrRep = np.repeat(arr, 3, axis=0)
print(arrRep)


[[1 2 3]
 [1 2 3]
 [1 2 3]]
