# Numpy Basic

In [2]:
import numpy as np
np.__version__

'1.24.2'

#### Adding two arrays

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3], dtype = 'int32')
arr3 = arr1 + arr2
print(arr3)

[2 4 6]


### get data type && size && Total size

In [14]:
print("Type:", arr2.dtype)
print("Size of array:", arr2.size)
print("Size of one element:", arr2.itemsize)
print("Total Size:", arr2.nbytes)

Type: int32
Size of array: 3
Size of one element: 4
Total Size: 12


# Multi_Dimensional array Basics

In [11]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
arr3D = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print("arr2D:", arr2D)
print("arr3D:", arr3D)

arr2D: [[1 2 3]
 [4 5 6]]
arr3D: [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


### get dimensions

In [12]:
print("arr2D:", arr2D.ndim)
print("arr3D:", arr3D.ndim)

arr2D: 2
arr3D: 3


### get Shape

In [13]:
print(arr2D.shape)
print(arr3D.shape)

(2, 3)
(1, 3, 3)


# Accessing/Changing specific elements, rows, columns, etc.

In [12]:
arr2D = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print("arr2D:", arr2D)
print("arr3D:", arr3D)


arr2D: [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr3D: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


### get specific index value

In [17]:
print("arr2D:", arr2D[1, 1])
print("arr3D:", arr3D[1, 1, 1])


arr2D: 5
arr3D: 11


### get specific row && column

In [26]:
print("Row:-")
print("arr2D:", arr2D[0, :])

print("\nColumn:-")
print("arr2D:", arr2D[:, 0])

print("\nRow [1->2]:-")
print("arr2D:", arr2D[0, 1: 2])


Row:-
arr2D: [91  2  3]

Column:-
arr2D: [91  4  7]

Row [1->2]:-
arr2D: [2]


### changing value

In [27]:
print("arr2D {Before change}:", arr2D)
arr2D[0, 0] = 91
print("\narr2D {After change}:", arr2D)

arr2D {Before change}: [[91  2  3]
 [ 4  5  6]
 [ 7  8  9]]

arr2D {After change}: [[91  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [28]:
print("arr2D {Before change}:", arr2D)
arr2D[1, 0] = arr2D[0, 0]
print("\narr2D {After change}:", arr2D)


arr2D {Before change}: [[91  2  3]
 [ 4  5  6]
 [ 7  8  9]]

arr2D {After change}: [[91  2  3]
 [91  5  6]
 [ 7  8  9]]
