# Numpy Basic

In [2]:
import numpy as np
np.__version__

'1.24.2'

#### Adding two Arrays

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3], dtype = 'int32')
arr3 = arr1 + arr2
print(arr3)

[2 4 6]


#### get data type && size && Total size

In [14]:
print("Type:", arr2.dtype)
print("Size of array:", arr2.size)
print("Size of one element:", arr2.itemsize)
print("Total Size:", arr2.nbytes)

Type: int32
Size of array: 3
Size of one element: 4
Total Size: 12


## Multi_Dimensional Array Basics

In [11]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
arr3D = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print("arr2D:", arr2D)
print("arr3D:", arr3D)

arr2D: [[1 2 3]
 [4 5 6]]
arr3D: [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


#### get dimensions

In [12]:
print("arr2D:", arr2D.ndim)
print("arr3D:", arr3D.ndim)

arr2D: 2
arr3D: 3


#### get Shape

In [13]:
print(arr2D.shape)
print(arr3D.shape)

(2, 3)
(1, 3, 3)


## Organizing Arrays

#### Reshaping Array

In [94]:
arr = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

print("Original array:\n ", arr)
print("\nReshaped array:\n ", arr.reshape((5,2)))


Original array:
  [[1 2 3 4 5]
 [1 2 3 4 5]]

Reshaped array:
  [[1 2]
 [3 4]
 [5 1]
 [2 3]
 [4 5]]


#### Vertical Stacking Array

In [96]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(np.vstack([arr1, arr2]))

[[1 2 3 4]
 [5 6 7 8]]


#### Horizontal Stacking Array

In [98]:
arr1 = np.ones((2,2))
arr2 = np.zeros((2,2))

print(np.hstack([arr1, arr2]))

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]


## Copy issue handled (Numpy)

#### Bug

In [42]:
arr1 = np.array([1, 2, 3])
arr2 = arr1
arr2[1] = 5

print ('arr1: ', arr1)
print ('arr2: ', arr2)

arr1:  [1 5 3]
arr2:  [1 5 3]


#### Fix

In [43]:
arr1 = np.array([1, 2, 3])
arr2 = arr1.copy()
arr2[1] = 5

print('arr1: ', arr1)
print('arr2: ', arr2)


arr1:  [1 2 3]
arr2:  [1 5 3]


## Accessing/Changing specific elements, rows, columns, etc.

In [12]:
arr2D = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print("arr2D:", arr2D)
print("arr3D:", arr3D)


arr2D: [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr3D: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


#### get specific index value

In [17]:
print("arr2D:", arr2D[1, 1])
print("arr3D:", arr3D[1, 1, 1])


arr2D: 5
arr3D: 11


#### get specific row && column

In [26]:
print("Row:-")
print("arr2D:", arr2D[0, :])

print("\nColumn:-")
print("arr2D:", arr2D[:, 0])

print("\nRow [1->2]:-")
print("arr2D:", arr2D[0, 1: 2])


Row:-
arr2D: [91  2  3]

Column:-
arr2D: [91  4  7]

Row [1->2]:-
arr2D: [2]


#### changing value

In [27]:
print("arr2D {Before change}:", arr2D)
arr2D[0, 0] = 91
print("\narr2D {After change}:", arr2D)

arr2D {Before change}: [[91  2  3]
 [ 4  5  6]
 [ 7  8  9]]

arr2D {After change}: [[91  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [28]:
print("arr2D {Before change}:", arr2D)
arr2D[1, 0] = arr2D[0, 0]
print("\narr2D {After change}:", arr2D)


arr2D {Before change}: [[91  2  3]
 [ 4  5  6]
 [ 7  8  9]]

arr2D {After change}: [[91  2  3]
 [91  5  6]
 [ 7  8  9]]


## Initializing Different types of Arrays

#### Initialize array with 0s

In [12]:
arr = np.zeros((2,2), dtype = 'int32')
print(arr)

[[0 0]
 [0 0]]


#### Initialize array with 1s

In [10]:
arr = np.ones((2, 2))
print(arr)


[[1. 1.]
 [1. 1.]]


#### Initialize Array with same data

In [14]:
arr = np.full((2, 2), 91)
print(arr)

[[91 91]
 [91 91]]


#### Initialize same structure Array with same other data

In [17]:
arr2 = np.full_like(arr, 2)
print(arr2)

[[2 2]
 [2 2]]


#### Initialize Array with random data

In [20]:
arr = np.random.rand(2,2)
print(arr)

[[0.79605027 0.9532402 ]
 [0.3428798  0.00303103]]


#### Initialize same structure array with random data

In [27]:
arr = np.random.random_sample(arr2.shape)
print(arr)


[[0.44946068 0.72778857]
 [0.2962834  0.0092902 ]]


#### Initialize with random integers with range

In [29]:
arr = np.random.randint(1, 10, size = (3,3))
print(arr)

[[1 7 6]
 [4 2 5]
 [9 7 7]]


#### Identity matrix formation

In [33]:
arr = np.identity(3, dtype = 'int32')
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### initialize Array with repeated values

In [37]:
arr = np.array([1, 2, 3])
arrRep = np.repeat(arr, 3, axis = 0)
print(arrRep)

[1 1 1 2 2 2 3 3 3]


In [38]:
arr = np.array([[1, 2, 3]])
arrRep = np.repeat(arr, 3, axis=0)
print(arrRep)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Mathematics

#### + - * / ^ (with numbers)

In [3]:
arr = np.array([1, 2, 3])

print('+ : ', arr + 2)
print('- : ', arr - 2)
print('* : ', arr * 2)
print('/ : ', arr / 2)
print('^ : ', arr ** 2)

+ :  [3 4 5]
- :  [-1  0  1]
* :  [2 4 6]
/ :  [0.5 1.  1.5]
^ :  [1 4 9]


#### + - * / ^ (with second array)

In [4]:
arr = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print('+ : ', arr + arr2)
print('- : ', arr - arr2)
print('* : ', arr * arr2)
print('/ : ', arr / arr2)
print('^ : ', arr ** arr2)


+ :  [2 4 6]
- :  [0 0 0]
* :  [1 4 9]
/ :  [1. 1. 1.]
^ :  [ 1  4 27]


#### Trigonometry 

In [57]:
arr = np.array([1, 2, 3])

print('cos: ', np.cos(arr))
print('sin: ', np.sin(arr))
print('tan: ', np.tan(arr))

cos:  [ 0.54030231 -0.41614684 -0.9899925 ]
sin:  [0.84147098 0.90929743 0.14112001]
tan:  [ 1.55740772 -2.18503986 -0.14254654]


#### Matrix(Linear algebra) to Array

#### Matrix Multiplication

In [4]:
arr1 = np.full((2,3), 2)
arr2 = np.full((3,2), 1)

print(np.matmul(arr1, arr2))

[[6 6]
 [6 6]]


#### Find Determinant

In [12]:
arr = np.array([[2, 1], [6, 5]])
print(np.linalg.det(arr))

3.999999999999999


#### Find inverse

In [13]:
arr = np.array([[2, 1], [6, 5]])
print(np.linalg.inv(arr))

[[ 1.25 -0.25]
 [-1.5   0.5 ]]


#### Statistics

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('Max: ', np.max(arr))
print('Max array: ', np.max(arr, axis = 0))
print('Max of every index: ', np.max(arr, axis = 1))

print('\nMin: ', np.min(arr))
print('Min array: ', np.min(arr, axis = 0))
print('Mai of every index: ', np.min(arr, axis=1))

print('\nSum of arrays: ', np.sum(arr))
print('Sum of arrays by same index: ', np.sum(arr, axis = 0))
print('Sum of each arrays: ', np.sum(arr, axis = 1))


Max:  9
Max array:  [7 8 9]
Max of every index:  [3 6 9]

Min:  1
Min array:  [1 2 3]
Mai of every index:  [1 4 7]

Sum of arrays:  45
Sum of arrays by same index:  [12 15 18]
Sum of each arrays:  [ 6 15 24]


## Load data from file

In [14]:
# TODO: left this part because it needs a file that contains data